### ISSUE TITLE
Jekit asking for permissions for public repo

### ISSUE THREAD

**Issue by ajb** [codeforamerica/git-jekyll-preview#2]
#### Steps to reproduce:

[http://jekit.codeforamerica.org/dobtco/splash](http://jekit.codeforamerica.org/dobtco/splash)

p.s. this project is super, super rad :)

**Comment by migurski** [comment]
Huh, that's odd. I will investigate. Because Github's API often responds with 404s instead of 401s (they don't want to leak private information) I often interpret the former as reason to authenticate. In this case though I would expect http://jekit.codeforamerica.org/dobtco/splash/gh-pages/ to simply work. And thanks!

**Comment by ajb** [comment]
Think we're safe to close this now.

**Comment by BretFisher** [comment]
This is happening for me on any public repo I try to run through jekit, including the link you put above @migurski

**Comment by migurski** [comment]
Thanks @BretFisher, I’ve put this aside for some time but I will look again.
